"""Generated by ordas. Do not edit.

Asserts that the DAG beside this imports, that it carries one task, and that
it still declares the process it was generated for.

It does NOT test the work. Nothing here runs a segment or reaches a broker, so
a pass means well-formed and says nothing about correct.
"""

import importlib.util
import pathlib

NAME = "request_triage__triage_priority"
DAG_PATH = pathlib.Path(__file__).resolve().parents[1] / "dags" / (NAME + ".py")
SOURCE_SHA256 = "a49205192d244b5895b5225a8a9a0f39e8118c31a4a576471825ba77aa7388e0"


def load():
    spec = importlib.util.spec_from_file_location(NAME, DAG_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_the_dag_imports():
    assert load().dag.dag_id == "ordas__request_triage__triage_priority"


def test_one_task_because_a_segment_runs_whole():
    tasks = [t.task_id for t in load().dag.tasks]
    assert tasks == ["triage_priority"], tasks


def test_it_declares_its_place_in_the_process():
    module = load()
    assert module.ORDAS_PROCESS == "request-triage"
    assert module.ORDAS_SEGMENT == 1
    assert module.ORDAS_SEGMENT_COUNT == 1
    assert module.ORDAS_STEP_ID == "request-triage/1/triage-priority"


def test_it_names_the_inputs_it_came_from():
    assert load().ORDAS_SOURCE_SHA256 == SOURCE_SHA256
