"""ordas__access_request__grant_approved -- segment 2 of 2 of access-request.

GENERATED BY ORDAS. Do not edit.

Editing this file is not forbidden, it is measured. ORDAS_SOURCE_SHA256 below
is a hash of the inputs this was generated from, and the evidence block beside
it carries a hash of this file's contents. An edit that leaves the first alone
and moves the second is a hand-edit, which is the number Gate C is asking for.
Editing it anyway and saying so is more useful than a clean regeneration that
hides what had to change.

This DAG is a schedule and not a program. It contains no branch, no loop and
no error handling, because every such line would be behaviour that the test
suite behind the command below cannot reach. If something here has to depend on
what a step did, that decision belongs there and not here, and this file learns
about it as a task that succeeded or failed.

One task, and that is the whole segment. The command resolves this segment's
spine completely before it writes anything, so a run that cannot finish has
written nothing. A task per step would hand the gap between steps to the
scheduler, and the scheduler failing between tasks is ordinary.
"""

import datetime

from airflow import DAG
from airflow.operators.bash import BashOperator

ORDAS_PROCESS = "access-request"
ORDAS_UNIT = "grant-approved"
ORDAS_SEGMENT = 2
ORDAS_SEGMENT_COUNT = 2
ORDAS_STEP_ID = "access-request/2/grant-approved"
ORDAS_SCOPE = "servicedesk/access-request/grant-approved"
ORDAS_RESUME_ON = "Approved"
ORDAS_PARKS_AT = ""
ORDAS_EMITTER = "emit/1"
ORDAS_SOURCE_SHA256 = "dd30691158baae26fb972e5e3a248c02715755a99266f9032248758fe62122e4"

with DAG(
    dag_id="ordas__access_request__grant_approved",
    description="access-request segment 2/2; resumes on 'Approved'",
    schedule=None,
    start_date=datetime.datetime(2026, 1, 1, tzinfo=datetime.UTC),
    catchup=False,
    max_active_runs=8,
    default_args={
        "retries": 2,
        "retry_delay": datetime.timedelta(seconds=60),
    },
    tags=[
        "ordas",
        "ordas-process:access-request",
        "ordas-segment:2-of-2",
        "ordas-source:dd30691158ba",
    ],
) as dag:
    BashOperator(
        task_id="grant_approved",
        bash_command="ordasrun -timeout 120s",
        append_env=True,
        env={
            "ORDAS_BROKER": "http://ordas-broker.internal:8080",
            "ORDAS_CANDIDATE": "grant-approved",
            "ORDAS_SCOPE": "servicedesk/access-request/grant-approved",
            "ORDAS_STEP": "access-request/2/grant-approved",
            "ORDAS_EPISODE": "{{ run_id }}",
            "ORDAS_ENVELOPE": "{{ dag_run.conf['envelope'] | tojson }}",
            "ORDAS_RESUME_OF": "{{ dag_run.conf['resume_of'] }}",
        },
    )
