"""ordas__request_triage__triage_priority -- segment 1 of 1 of request-triage.

GENERATED BY ORDAS. Do not edit.

Editing this file is not forbidden, it is measured. ORDAS_SOURCE_SHA256 below
is a hash of the inputs this was generated from, and the evidence block beside
it carries a hash of this file's contents. An edit that leaves the first alone
and moves the second is a hand-edit, which is the number Gate C is asking for.
Editing it anyway and saying so is more useful than a clean regeneration that
hides what had to change.

This DAG is a schedule and not a program. It contains no branch, no loop and
no error handling, because every such line would be behaviour that the test
suite behind the command below cannot reach. If something here has to depend on
what a step did, that decision belongs there and not here, and this file learns
about it as a task that succeeded or failed.

One task, and that is the whole segment. The command resolves this segment's
spine completely before it writes anything, so a run that cannot finish has
written nothing. A task per step would hand the gap between steps to the
scheduler, and the scheduler failing between tasks is ordinary.

THIS FILE DOES NOT SAY WHAT THE WORK IS. It says when the work runs. What the
work reads and writes is described in

    spine/request_triage__triage_priority.md

and reviewing this schedule without reading that file is approving a
bash_command. That is not a caveat about thoroughness: the schedule is the part
with no risk in it.
"""

import datetime

from airflow import DAG
from airflow.operators.bash import BashOperator

ORDAS_PROCESS = "request-triage"
ORDAS_UNIT = "triage-priority"
ORDAS_SEGMENT = 1
ORDAS_SEGMENT_COUNT = 1
ORDAS_STEP_ID = "request-triage/1/triage-priority"
ORDAS_SCOPE = "servicedesk/request-triage"
ORDAS_RESUME_ON = ""
ORDAS_PARKS_AT = ""
ORDAS_EMITTER = "emit/1"
ORDAS_SOURCE_SHA256 = "a49205192d244b5895b5225a8a9a0f39e8118c31a4a576471825ba77aa7388e0"

with DAG(
    dag_id="ordas__request_triage__triage_priority",
    description="request-triage segment 1/1",
    schedule=None,
    start_date=datetime.datetime(2026, 1, 1, tzinfo=datetime.UTC),
    catchup=False,
    max_active_runs=8,
    default_args={
        "retries": 2,
        "retry_delay": datetime.timedelta(seconds=60),
    },
    tags=[
        "ordas",
        "ordas-process:request-triage",
        "ordas-segment:1-of-1",
        "ordas-source:a49205192d24",
    ],
) as dag:
    BashOperator(
        task_id="triage_priority",
        bash_command="ordasrun -timeout 120s",
        append_env=True,
        env={
            "ORDAS_BROKER": "http://ordas-broker.internal:8080",
            "ORDAS_CANDIDATE": "triage-priority",
            "ORDAS_SCOPE": "servicedesk/request-triage",
            "ORDAS_STEP": "request-triage/1/triage-priority",
            "ORDAS_EPISODE": "{{ run_id }}",
            "ORDAS_ENVELOPE": "{{ dag_run.conf['envelope'] | tojson }}",
        },
    )
